// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace BoxTI.Challenge.CovidTracking.API.Models
{
    [Table("Country")]
    public partial class Country
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "decimal(10, 0)")]
        public decimal? ActiveCases { get; set; }
        [Required]
        [StringLength(50)]
        public string CountryName { get; set; }
        [Column(TypeName = "date")]
        public DateTime? LastUpdate { get; set; }
        [Column(TypeName = "decimal(10, 0)")]
        public decimal? NewCases { get; set; }
        [Column(TypeName = "decimal(10, 0)")]
        public decimal? NewDeaths { get; set; }
        [Column(TypeName = "decimal(10, 0)")]
        public decimal? TotalCases { get; set; }
        [Column(TypeName = "decimal(10, 0)")]
        public decimal? TotalDeaths { get; set; }
        [Column(TypeName = "decimal(10, 0)")]
        public decimal? TotalRecovered { get; set; }
        public bool IsDeleted { get; set; }
    }
}